# Generated by Django 5.0 on 2024-10-11 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mittais', '0002_movie_description_movie_price_movie_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mittais.cart')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mittais.movie')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='movies',
            field=models.ManyToManyField(through='mittais.CartItem', to='mittais.movie'),
        ),
    ]
