# Generated by Django 5.0 on 2024-10-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mittais', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='movies',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mittais.cart'),
        ),
    ]
