# Generated by Django 5.0 on 2024-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mittais', '0009_newlaunch_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbrands',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
